//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::descriptions::Entity as Descriptions;
pub use super::favicons::Entity as Favicons;
pub use super::ips::Entity as Ips;
pub use super::players::Entity as Players;
pub use super::servers::Entity as Servers;
